### ISSUE TITLE
Not all sms and call measurement SQL insert statements are executed correctly

### ISSUE THREAD

**Issue by sneJ-** [datagiraffe/cellservice#9]
For some I get a NullPoinerException.

##Received Call

05-12 12:01:59.470 30862-317/de.tu_berlin.snet.trappjectories E/GEODBH_JSQLITE: Inserting measurement sql: INSERT INTO Measurements (cell_id, provider, accuracy, centroid, event, time)   VALUES (1, 'network', 25.115, GeomFromText('POINT(13.5581825 52.5263795)', 4326), 'call', 1463047235);
05-12 12:01:59.530 30862-317/de.tu_berlin.snet.trappjectories W/System.err: java.lang.NullPointerException
05-12 12:01:59.531 30862-317/de.tu_berlin.snet.trappjectories W/System.err:     at de.tu_berlin.snet.cellservice.model.database.GeoDatabaseHelper$1.run(GeoDatabaseHelper.java:222)
05-12 12:01:59.531 30862-317/de.tu_berlin.snet.trappjectories W/System.err:     at java.lang.Thread.run(Thread.java:841)
05-12 12:01:59.532 30862-317/de.tu_berlin.snet.trappjectories W/System.err: java.lang.NullPointerException
05-12 12:01:59.532 30862-317/de.tu_berlin.snet.trappjectories W/System.err:     at de.tu_berlin.snet.cellservice.model.database.GeoDatabaseHelper$1.run(GeoDatabaseHelper.java:222)
05-12 12:01:59.532 30862-317/de.tu_berlin.snet.trappjectories W/System.err:     at java.lang.Thread.run(Thread.java:841)

##Received SMS

05-12 12:09:26.670 3746-4922/de.tu_berlin.snet.trappjectories E/GEODBH_JSQLITE: Inserting measurement sql: INSERT INTO Measurements (cell_id, provider, accuracy, centroid, event, time)   VALUES (2, 'network', 25.347, GeomFromText('POINT(13.5581867 52.5263758)', 4326), 'text message', 1463047731);
05-12 12:09:26.702 3746-4922/de.tu_berlin.snet.trappjectories W/System.err: java.lang.NullPointerException
05-12 12:09:26.702 3746-4922/de.tu_berlin.snet.trappjectories W/System.err:     at de.tu_berlin.snet.cellservice.model.database.GeoDatabaseHelper$1.run(GeoDatabaseHelper.java:222)
05-12 12:09:26.702 3746-4922/de.tu_berlin.snet.trappjectories W/System.err:     at java.lang.Thread.run(Thread.java:841)
05-12 12:09:26.702 3746-4922/de.tu_berlin.snet.trappjectories W/System.err: java.lang.NullPointerException
05-12 12:09:26.702 3746-4922/de.tu_berlin.snet.trappjectories W/System.err:     at de.tu_berlin.snet.cellservice.model.database.GeoDatabaseHelper$1.run(GeoDatabaseHelper.java:222)
05-12 12:09:26.702 3746-4922/de.tu_berlin.snet.trappjectories W/System.err:     at java.lang.Thread.run(Thread.java:841)

05-12 12:10:57.953 3746-3746/de.tu_berlin.snet.trappjectories E/CursorLeakDetecter: PossibleCursorLeak:content://sms/sent,QueryCounter:5
                                                                                    android.database.sqlite.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
                                                                                        at android.content.ContentResolver.query(ContentResolver.java:491)
                                                                                        at android.content.ContentResolver.query(ContentResolver.java:405)
                                                                                        at de.tu_berlin.snet.cellservice.observer.OutgoingSMSObserver.checkForTextMessages(OutgoingSMSObserver.java:70)
                                                                                        at de.tu_berlin.snet.cellservice.observer.OutgoingSMSObserver.onChange(OutgoingSMSObserver.java:100)
                                                                                        at android.database.ContentObserver.onChange(ContentObserver.java:129)
                                                                                        at android.database.ContentObserver$NotificationRunnable.run(ContentObserver.java:180)
                                                                                        at android.os.Handler.handleCallback(Handler.java:808)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                                        at android.os.Looper.loop(Looper.java:193)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5327)
                                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                        at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
                                                                                        at dalvik.system.NativeStart.main(Native Method)

**Comment by sneJ-** [comment]
Most probably the reason was my deactivated GPS

**Comment by datagiraffe** [comment]
It shouldn't be. If the GPS is disabled nothing broke for me.

**Comment by datagiraffe** [comment]
Have you tried removing your database to have a clean state?

**Comment by sneJ-** [comment]
Did it once again. GPS disabled. Database deleted. Opened the App. Started the services. Called myself. Stopped the service. No entries in the measurements table.

Attached you'll find the logcat and spatial database.
[log.zip](https://github.com/datagiraffe/cellservice/files/261849/log.zip)

**Comment by datagiraffe** [comment]
Oh I see.
The Call is actually created. (Twice?!, which is odd)
But there are no measurements.

If you don't have GPS enabled, the LocationFuture for GPS will obviously fail and not be able to retrieve a GPS location.
Now there is only a chance for a network location to be retrieved. Getting a network location requires an internet connection (to send either the cellid / lac to or visible WiFi APs to Google)

For a call, this is not attempted, as it would create a new Data Record - which would otherwise not be created and thus falsifies the real network usage. <a href="https://github.com/datagiraffe/cellservice/commit/5501f8c7f9cd214d3ed766dc32b0300397283e5e#diff-78a8647ba7e8c148a45c5a98ea16af48R158">Only if there is a WiFi connection</a>, a network location will be attempted to be received. _I'm not sure how reliable this is._

But even this process can fail. Google cannot always resolve your location.
